export const state = {
    data:null,
    links:null,
    meta:null,
    isLoading:false,
    error:null,
    productDetail:null,
    validationPage: null,
    categories:[
        {
            "id":1,
            "name":"Telefon",
        },
        {
            "id":2,
            "name":"Planshet",
        },
        {
            "id":3,
            "name":"Noutbuk",
        }
        ],

        brands: [
            {
                "id":1,
                "category_id":1,
                "name":"Nokia"
            },
            {
                "id":2,
                "category_id":1,
                "name":"Realme"
            },
            {
                "id":3,
                "category_id":1,
                "name":"Redmi"
            },
            {
                "id":4,
                "category_id":2,
                "name":"Samsung"
            },
            {
                "id":5,
                "category_id":2,
                "name":"Redmi"
            },
            {
                "id":6,
                "category_id":2,
                "name":"Iphone"
            },
            {
                "id":7,
                "category_id":3,
                "name":"Asus"
            },
            {
                "id":8,
                "category_id":3,
                "name":"Hp"
            },
            {
                "id":9,
                "category_id":3,
                "name":"Dell"
            },
        ]
}